export default function Methodology() {
  return <section className="card lh-methodology" id="method"><details><summary>Personal context. Transparent rules. <span className="muted">How your brief is made</span></summary>
    <div>
      <p>This is wellness guidance, not medical advice or a diagnosis. These transparent rules are conservative product heuristics, not clinically validated medical thresholds. No AI service or population HRV norms are used.</p>
      <p><strong>Baselines:</strong> the previous 7 and 30 calendar days, excluding today, in your browser’s time zone. Averages require at least 4 and 15 valid days respectively, and incomplete windows are labeled. Sleep and recovery are dated by wake time; cycle strain is dated by cycle start. The latest main sleep and cycle on a date are used, without summing nonlinear strain scores. Naps, unscored records and calibrating recoveries are excluded.</p>
      <p><strong>Trends:</strong> the last 3 consecutive days compared with the preceding 7 days, with at least 4 earlier readings. The recent average and at least 2 recent days must cross the change threshold in the same direction. HRV needs a change above 10% or 1 ms, resting heart rate above 5% or 2 bpm, and sleep duration above 5% or 0.3 hours, whichever is larger. Recovery decline also affects training advice, using 10% or 1 percentage point, whichever is larger. Sleep trends describe duration, not all aspects of sleep quality. Unknown is null, never “stable.”</p>
      <p><strong>Training:</strong> sustained lower HRV, higher resting heart rate or shorter sleep favor lighter activity. A single-day HRV drop above 30%, resting heart rate rise of at least 20% and 10 bpm, or recovery drop above 25 percentage points can also change advice. The reference is your available 30-day average, falling back to the 7-day average. WHOOP recovery colors use its own score bands, not a medical risk rating.</p>
      <p><strong>Patterns:</strong> at least two higher-strain/next-day lower-recovery pairs are required, compared with the earlier 7-day baseline. A shorter-sleep/HRV link requires at least 10 paired nights, with at least 3 shorter and 3 other nights. Associations are not causes.</p>
      <p><strong>Health flags:</strong> blood oxygen below 92% on at least 2 of the last 7 days; resting heart rate increasing at least 2 bpm on each of 3 consecutive days, with a total rise of at least 20% and 10 bpm; or breathing rate at least 20% and 3 breaths/min above an earlier personal baseline for 3 days. A single breathing-rate rise of at least 30% and 5 breaths/min is also flagged. Breathing comparisons require at least 7 earlier readings. A missing flag is not medical clearance.</p>
      <p><strong>Privacy:</strong> tokens and data are held only in this Node process, for up to a day; raw API responses are cached for a minute. Restarting the server signs you out. No health data is put in browser storage or sent to an AI provider. Live Health is isolated from the synthetic patient records, demo reset, and shared provider activity feed. This single-process setup needs a secure shared session store before multi-instance deployment. Optional age and sex are not used to infer missing values or population-based targets.</p>
    </div>
  </details></section>;
}
